apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-v2
  namespace: webapp
  labels:
    app: employees
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v2
  template:
    metadata:
      labels:
        app: employees
        version: v2
    spec:
      containers:
        - name: webapp-container
          image: '248647995044.dkr.ecr.us-east-1.amazonaws.com/webapp:v2'
          env:
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: dbpass
            - name: DBHOST
              value: "mysql-service.sqldb"
            - name: DBPORT
              value: '3306'
            - name: APP_COLOR
              value: green
          ports:
            - containerPort: 8080
