apiVersion: v1
kind: Service
metadata:
  name: webapp-service-v2
  namespace: webapp
  labels:
    app: employees
    version: v2
spec:
  type: NodePort
  selector:
    app: employees
    version: v2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
