apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: webapp
spec:
  containers:
    - name: webapp-container
      image: 248647995044.dkr.ecr.us-east-1.amazonaws.com/webapp:v1
      env:
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: dbpass
        - name: DBHOST
          value: #mysql-pod-ip
        - name: DBPORT
          value: "3306"
        - name: APP_COLOR
          value: pink
      ports:
        - containerPort: 8080
