apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: sqldb
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: '248647995044.dkr.ecr.us-east-1.amazonaws.com/mysqldb:v1'
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: dbpass
          ports:
            - containerPort: 3306
