apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: sqldb
spec:
  containers:
    - name: mysql-container
      image: '248647995044.dkr.ecr.us-east-1.amazonaws.com/mysqldb:v1'
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: dbpass
      ports:
        - containerPort: 3306
